import { z } from "zod";
import { chatCompletion } from "./nanogpt.js";
import { MAX_TOKEN_CHARS } from "./typography3d.js";

/**
 * Creative Brief — Задание 3, Фаза 2. Промпт кампании → структура сцены.
 *
 * Закрывает претензию П-1 «промпт не участвует в композиции», и только её.
 * Персонаж и предмет уже генерируются работающим пайплайном (`D-N10`):
 * `buildBundleItemPrompt(brand, neuralPrompt)` подставляет текст кампании в
 * обёртку бренда, `getPersonSystemPrompt(brand)` + `BrandNanoRef` дают
 * персонажа. Бриф их НЕ описывает и промптов для них не пишет.
 *
 * Ему остаётся ровно то, чего сегодня нет: свет, декор, сезон, палитра и
 * заполнены ли опциональные слоты надписей.
 *
 * Надмножество прежнего `styleProfile` (`PROMPT-CONTRACT.md` §7):
 * `glowHex` → `paletteHint` + `lightMood`, `tokens` → `captions`,
 * `density` → коридоры спеки, `decorUrls` → `decorConcepts` по тегам.
 */

export const OFFER_KINDS = [
  "welcome",
  "deposit_bonus",
  "reload",
  "free_spins",
  "cashback",
  "tournament",
  "seasonal",
  "vip",
  "drop_and_win",
] as const;

export const MOODS = [
  "celebration",
  "luxury",
  "mystery",
  "action",
  "cozy",
  "seasonal",
] as const;

export const SEASONS = [
  "sakura",
  "tropics",
  "summer",
  "winter",
  "christmas",
  "halloween",
  "easter",
  "lunar_new_year",
] as const;

/** Концепт декора: короткое родовое существительное, только латиница. */
export const CONCEPT_RE = /^[a-z_]{2,20}$/;
/** Не больше двух надписей на кадр: слоты `left-fill` и `held`. */
export const MAX_CAPTIONS = 2;
export const MAX_DECOR_CONCEPTS = 6;

export const creativeBriefSchema = z.object({
  offer: z.object({
    kind: z.enum(OFFER_KINDS),
    headline: z.string().max(40).nullable(),
    amount: z.string().max(40).nullable(),
    extras: z.array(z.string().max(60)).max(3).default([]),
    cta: z.string().max(30).nullable(),
  }),
  mood: z.enum(MOODS),
  season: z.enum(SEASONS).nullable(),
  decorConcepts: z.array(z.string()).max(MAX_DECOR_CONCEPTS).default([]),
  paletteHint: z.string().max(60).nullable(),
  lightMood: z.string().max(80),
  captions: z.array(z.string().max(MAX_TOKEN_CHARS)).max(MAX_CAPTIONS).default([]),
  confidence: z.object({ offer: z.number(), scene: z.number() }),
});

export type CreativeBrief = z.infer<typeof creativeBriefSchema>;

// ---------------------------------------------------------------------------
// Промпт
// ---------------------------------------------------------------------------

export const CREATIVE_BRIEF_SYSTEM_PROMPT = [
  "You are a creative director for casino CRM promo banners.",
  "",
  "The character and the main object are generated by a separate pipeline",
  "that already knows this brand. You do NOT describe them. You do NOT",
  "write prompts for them.",
  "",
  "Your job is the SCENE around them: light, decor, season, palette, and",
  "whether the optional caption slots are used.",
  "",
  "The frame is always built the same way and you never change it:",
  "  - the main object stands on the left,",
  "  - the character stands on the right,",
  "  - the centre is reserved for the email text and must stay clear,",
  "  - decor fills the space above and below that centre.",
  "",
  "Return a single JSON object and nothing else. No markdown, no prose,",
  "no code fences.",
  "",
  "{",
  '  "offer": {',
  '    "kind": "<one of the offer kinds below>",',
  '    "headline": "<short line above the amount, or null>",',
  '    "amount": "<the amount exactly as written in the brief, or null>",',
  '    "extras": ["<secondary offer lines>"],',
  '    "cta": "<button text, or null>"',
  "  },",
  '  "mood": "<one of the moods below>",',
  '  "season": "<one of the seasons below, or null>",',
  '  "decorConcepts": ["<short English nouns: what small objects suit this campaign>"],',
  '  "paletteHint": "<2-3 dominant colours as words, or null>",',
  '  "lightMood": "<one short phrase describing the lighting of the scene>",',
  '  "captions": ["<up to 2 ALL-CAPS captions, max 14 chars, or empty>"],',
  '  "confidence": { "offer": 0..1, "scene": 0..1 }',
  "}",
  "",
  "Hard rules:",
  "",
  "1. Leave a field null or empty when the brief does not say it. Do NOT",
  "   invent an amount, a headline or a CTA. A guessed number reaches a",
  "   real customer.",
  "2. `captions` may only contain wording that appears in the brief, or be",
  "   empty. An empty array is a normal, valid answer — the frame works",
  "   without captions. Never add a generic caption like BIG WIN just to",
  "   fill the slot.",
  "3. `decorConcepts`: 3-6 short generic nouns for small props that suit the",
  "   campaign (for example: coin, chip, banknote, spark, star, petal,",
  "   gift_box, snowflake). Lowercase, singular, English, no adjectives.",
  "   These are concepts, not instructions — placement is decided elsewhere.",
  "4. `lightMood` describes ONLY light and atmosphere: colour of the glow,",
  "   its energy, its warmth. Never name an object, a character or a shape.",
  "5. Never output coordinates, positions, sizes, percentages or layout",
  "   words (left, right, centre, top, bottom). Layout is fixed.",
  "6. `paletteHint` is a suggestion. If the brief names no colour, use null",
  "   and let the brand's own palette win.",
  "",
  `Offer kinds: ${OFFER_KINDS.join(" | ")}`,
  `Moods: ${MOODS.join(" | ")}`,
  `Seasons: ${SEASONS.join(" | ")} | null`,
].join("\n");

export interface CreativeBriefRequest {
  /** Свободный текст менеджера — `Bundle.neuralPrompt`. */
  campaignPrompt: string;
  /** Выбранный пресет типа акции; пусто → "none". */
  presetKey?: string | null;
  brandName: string;
  assetKey: string;
  /**
   * Теги концептов наполненной библиотеки. ПОДСКАЗКА, а не белый список:
   * библиотека необязательна (`D-N7'`), и концепт, которого в ней нет, будет
   * сгенерирован листом декора.
   */
  availableConcepts?: string[];
}

export function buildCreativeBriefUserMessage(req: CreativeBriefRequest): string {
  const concepts = req.availableConcepts?.length
    ? req.availableConcepts.join(", ")
    : "(none — will be generated)";
  return [
    `Campaign preset: ${req.presetKey?.trim() || "none"}`,
    `Campaign brief: ${req.campaignPrompt.trim() || "(empty)"}`,
    `Brand: ${req.brandName}`,
    `Asset type: ${req.assetKey}`,
    `Decor already available for this brand: ${concepts}`,
  ].join("\n\n");
}

// ---------------------------------------------------------------------------
// Кламп: модель предлагает, код решает
// ---------------------------------------------------------------------------

/**
 * Слова, которыми `lightMood` описывать сцену не должен: это объекты и
 * раскладка, а не свет. Нарушение здесь дороже, чем кажется — `lightMood`
 * попадает в промпт генеративного слоя, а тот обязан остаться БЕЗ объектов,
 * иначе кейинг `alpha = f(яркость)` (`D-N6`) превратит нарисованную монету в
 * полупрозрачный призрак.
 */
const LIGHT_MOOD_BANNED = [
  "coin", "chip", "banknote", "money", "cash", "card", "dice", "star", "gift",
  "crown", "diamond", "bar", "petal", "leaf", "snowflake", "confetti", "balloon",
  "character", "person", "man", "woman", "girl", "boy", "dog", "cat", "animal",
  "mascot", "logo", "text", "letter", "number", "sign", "banner", "frame",
  "left", "right", "centre", "center", "top", "bottom", "corner",
];

/**
 * Контекст клампа — только промпт кампании.
 *
 * Списка доступных концептов здесь намеренно НЕТ: библиотека декора
 * необязательна (`D-N7'`), и концепт, которого в ней нет, не выбрасывается, а
 * уходит в генерацию листа декора (`D-N9'`). Белым списком библиотека была бы
 * ровно до первой сезонной акции.
 */
export interface ClampContext {
  campaignPrompt: string;
}

/** Буквы и цифры подряд, в верхнем регистре — для сравнения надписи с брифом. */
function alnumUpper(s: string): string {
  return s.toUpperCase().replace(/[^A-Z0-9А-ЯЁ]+/g, "");
}

/**
 * Надпись законна, только если она реально прозвучала в брифе (правило 2).
 * Сравнение по буквенно-цифровому «скелету»: «+50 FREE SPINS» в брифе и
 * надпись «50 FREE SPINS» — это одно и то же, а вот «BIG WIN» из воздуха — нет.
 */
export function captionAppearsInBrief(caption: string, brief: string): boolean {
  const c = alnumUpper(caption);
  if (c.length === 0) return false;
  const b = alnumUpper(brief);
  if (b.includes(c)) return true;
  // Либо каждое слово надписи встречается в брифе по отдельности.
  const words = caption.split(/\s+/).map(alnumUpper).filter((w) => w.length > 1);
  return words.length > 0 && words.every((w) => b.includes(w));
}

/**
 * Сумма законна, только если её цифры реально есть в брифе.
 *
 * Правило 1 системного промпта запрещает выдумывать сумму, но одной
 * инструкции мало: это самая дорогая из возможных ошибок — «500 000$»,
 * которых не было в кампании, уходит живому клиенту в письме. Надписи мы
 * уже проверяем по брифу; сумма заслуживает того же, и даже больше.
 *
 * Сравниваются ЦИФРЫ, а не строка целиком: «500 000$» в брифе и «500000$»
 * в ответе — одно и то же, а «1 000 000$» — уже нет.
 */
export function amountAppearsInBrief(amount: string, brief: string): boolean {
  const digits = amount.replace(/\D+/g, "");
  if (digits.length === 0) return true; // «up to 100 free spins» без числа в сумме
  return brief.replace(/\D+/g, "").includes(digits);
}

export function lightMoodNamesObject(lightMood: string, decorConcepts: string[]): boolean {
  const low = ` ${lightMood.toLowerCase().replace(/[^a-z ]+/g, " ")} `;
  const banned = [...LIGHT_MOOD_BANNED, ...decorConcepts.map((c) => c.replace(/_/g, " "))];
  return banned.some((w) => low.includes(` ${w} `) || low.includes(` ${w}s `));
}

/**
 * Приведение ответа модели к тому, что система готова исполнить. Схема
 * защищает от неверных ТИПОВ, кламп — от правдоподобной выдумки внутри
 * допустимых типов. Тот же приём, что в работающем `clampStyleProfile`.
 */
export function clampCreativeBrief(brief: CreativeBrief, ctx: ClampContext): CreativeBrief {
  const decorConcepts = [...new Set(brief.decorConcepts.map((c) => c.trim().toLowerCase()))]
    .filter((c) => CONCEPT_RE.test(c))
    .slice(0, MAX_DECOR_CONCEPTS);

  const captions = brief.captions
    .map((c) => c.trim().toUpperCase().replace(/\s+/g, " "))
    .filter((c) => c.length > 0 && c.length <= MAX_TOKEN_CHARS)
    .filter((c) => captionAppearsInBrief(c, ctx.campaignPrompt))
    .slice(0, MAX_CAPTIONS);

  const lightMood = lightMoodNamesObject(brief.lightMood, decorConcepts)
    ? ""
    : brief.lightMood.trim();

  // Сумма, которой не было в брифе, обнуляется вместе с ведущей строкой:
  // «UP TO» без числа под ним — это не оффер, а обрывок.
  const amountOk =
    brief.offer.amount === null || amountAppearsInBrief(brief.offer.amount, ctx.campaignPrompt);
  // D-N16: headline, extras и cta — дыра того же рода, что и сумма (D-N13).
  // Выдуманный «+50 FREE SPINS» уходит в `textOverlay.lines` письма ровно так
  // же, как выдуманные «500 000$». Правило одно на весь текст оффера: строка
  // законна, только если прозвучала в брифе; пустое поле заполняет конфиг
  // бренда, а не фантазия модели.
  const headlineOk =
    amountOk &&
    brief.offer.headline !== null &&
    captionAppearsInBrief(brief.offer.headline, ctx.campaignPrompt);
  const ctaOk =
    brief.offer.cta !== null && captionAppearsInBrief(brief.offer.cta, ctx.campaignPrompt);
  const offer = {
    ...brief.offer,
    amount: amountOk ? brief.offer.amount : null,
    headline: headlineOk ? brief.offer.headline : null,
    extras: brief.offer.extras.filter((e) => captionAppearsInBrief(e, ctx.campaignPrompt)),
    cta: ctaOk ? brief.offer.cta : null,
  };

  return {
    ...brief,
    offer,
    decorConcepts,
    captions,
    lightMood,
    // Числа уверенности приходят от модели и ни на что не влияют напрямую —
    // зажимаем в 0..1, чтобы они не портили логи и превью.
    confidence: {
      offer: clamp01(brief.confidence.offer),
      scene: clamp01(brief.confidence.scene),
    },
  };
}

function clamp01(v: number): number {
  if (!Number.isFinite(v)) return 0;
  return Math.min(1, Math.max(0, v));
}

// ---------------------------------------------------------------------------
// Вызов модели
// ---------------------------------------------------------------------------

/**
 * Один вызов на бандл. Любой сбой → `null`: рендер идёт на дефолтах бренда и
 * НЕ блокируется — то же правило, что у `styleProfile`, и оно не обсуждается.
 * Прослойка, роняющая генерацию из-за недоступной LLM, хуже её отсутствия.
 */
export async function requestCreativeBrief(
  req: CreativeBriefRequest,
): Promise<CreativeBrief | null> {
  const text = await chatCompletion(
    CREATIVE_BRIEF_SYSTEM_PROMPT,
    buildCreativeBriefUserMessage(req),
    // temperature 0: один и тот же бриф обязан давать один и тот же разбор,
    // иначе «повтор идентичен» из DoD Фазы 2 недостижим уже на первом шаге.
    { temperature: 0, maxTokens: 600 },
  );
  if (!text) return null;
  return parseCreativeBrief(text, { campaignPrompt: req.campaignPrompt });
}

/** Разбор ответа модели. Вынесен отдельно — тестируется без сети. */
export function parseCreativeBrief(text: string, ctx: ClampContext): CreativeBrief | null {
  // Модели любят заворачивать JSON в ```-ограду вопреки инструкции.
  const bare = text
    .replace(/^\s*```(?:json)?\s*/i, "")
    .replace(/\s*```\s*$/, "")
    .trim();
  let parsed: unknown;
  try {
    parsed = JSON.parse(bare);
  } catch {
    return null;
  }
  const res = creativeBriefSchema.safeParse(parsed);
  if (!res.success) return null;
  return clampCreativeBrief(res.data, ctx);
}
